name: Generate ISO

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.4.0
        id: build
        with:
          image_name: fedora-kinoite-nitro-an515-43
          image_repo: ghcr.io/${{ github.repository_owner }}
          image_tag: latest
          version: 43
          variant: Kinoite
          iso_name: fedora-kinoite-nitro-an515-43.iso

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fedora-kinoite-nitro-an515-43
          path: |
            ./fedora-kinoite-nitro-an515-43.iso
            ./fedora-kinoite-nitro-an515-43.iso-CHECKSUM
          if-no-files-found: error

      # Optional: Upload to Release if the workflow was triggered by a tag
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fedora-kinoite-nitro-an515-43.iso
            fedora-kinoite-nitro-an515-43.iso-CHECKSUM
